# Generated by Django 3.0.5 on 2020-05-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cashMovementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRequested', models.DateTimeField(blank=True, null=True)),
                ('withdrawlOrDeposit', models.CharField(default='', max_length=20)),
                ('amount', models.CharField(default='', max_length=20)),
                ('currency', models.CharField(default='', max_length=3)),
                ('provider', models.CharField(default='', max_length=20)),
                ('accountNumber', models.CharField(default='', max_length=20)),
                ('accountName', models.CharField(default='', max_length=200)),
                ('narrative', models.CharField(blank=True, default='', max_length=200)),
                ('sortCodeABACA', models.CharField(blank=True, default='', max_length=50)),
                ('bankAccountNumber', models.CharField(blank=True, default='', max_length=50)),
                ('IBAN', models.CharField(blank=True, default='', max_length=200)),
                ('Notifications', models.CharField(blank=True, default='', max_length=200)),
                ('asuraInternalNarrative', models.CharField(blank=True, default='', max_length=200)),
                ('asuraPaymentIDLloyds', models.CharField(blank=True, default='', max_length=200)),
                ('asuraPaymentIDProvider', models.CharField(blank=True, default='', max_length=200)),
                ('dateCompleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='', max_length=20)),
                ('accountNumber', models.CharField(default='', max_length=20)),
                ('accountName', models.CharField(default='', max_length=200)),
                ('currency', models.CharField(default='', max_length=3)),
                ('sortCodeABACA', models.CharField(blank=True, default='', max_length=50)),
                ('bankAccountNumber', models.CharField(blank=True, default='', max_length=50)),
                ('IBAN', models.CharField(blank=True, default='', max_length=200)),
                ('SWIFT', models.CharField(blank=True, default='', max_length=200)),
                ('presentOnDrive', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('dateVerified', models.CharField(default='', max_length=50)),
                ('timeVerified', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
