# Generated by Django 3.0.5 on 2020-06-02 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='dateVerified',
        ),
        migrations.RemoveField(
            model_name='clientaccount',
            name='timeVerified',
        ),
        migrations.AddField(
            model_name='cashmovementrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashmovementrequest',
            name='dateRequested',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='currency',
            field=models.CharField(default='', max_length=20),
        ),
    ]
