# Generated by Django 3.0.5 on 2020-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200602_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='user',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
