# Generated by Django 3.0.5 on 2020-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200602_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='user',
        ),
    ]
