# Generated by Django 3.0.5 on 2020-06-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_clientaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='dateVerified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
