# Generated by Django 3.0.5 on 2020-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_cashmovementrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovementrequest',
            name='userCompleted',
            field=models.CharField(default='', max_length=50),
        ),
    ]
