# Generated by Django 3.0.5 on 2020-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_cashmovementrequest_usercompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovementrequest',
            name='cancellationMessage',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
