# Generated by Django 3.0.5 on 2020-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_cashmovementrequest_cancellationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovementrequest',
            name='cancellationMessage',
            field=models.CharField(blank=True, default='', max_length=9999),
        ),
    ]
